manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: carrefinho                            # <--- add this
      url-base: https://github.com/carrefinho     # <--- and this
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    #add prospector screen feath
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: prospector
      url-base: https://github.com/t-ogura
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      #add display viev
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
 #   - name: prospector-zmk-module                 # <--- and these
 #     remote: carrefinho                          # <---
 #     revision: main                              # <---
    #- name: zmk
      #remote: petejohanson
      #revision: feat/pointers-move-scroll
      #import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    #add prospector screen feath
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    #add prospector screen with feath
    - name: prospector-zmk-module
      remote: prospector
      revision: v1.0.0
      path: modules/prospector-zmk-module
  self:
    path: config
